- samplr/kubernetes/deployment.yaml
- samplr/samplr-rtr/main.go
> fix(samplr-rtr): remove unused variables for samplr-rtr

- .kokoro/go113.cfg
- .kokoro/test.sh
- drghs-worker/maintnerd/main.go
Remove whitespace in .kokoro/test.sh
> fix(maintner): fix wrong formatting argument

- drghs-worker/pkg/status/get_issue_request.go
- drghs-worker/pkg/status/list_issue_request.go
- drghs-worker/pkg/status/response.go
- drghs-worker/utils/maintmigrate/main.go
> fix: drghs-worker passes go vet

- repos/go.mod
- repos/go.sum
- repos/repos_bucket.go
> fix(repos): fixed deserialization issue

- samplr/git-go/repository.go
- samplr/kubernetes/deployment.yaml
> fix(samplr): fixed formatting directive in FetchContext

- CONTRIBUTING.md
> chore: updated CONTRIBUTING.md

- drghs-worker/maintnerd/Dockerfile
> chore(maintnerd): add gRPC debugging

- sprvsr/k8s_supervisor.go
- sprvsr/k8s_supervisor_test.go
If a TrackedRepository's image will be changed somehow, roll out a new
version
> fix(sprvsr): images in the deployments trigger deletes

- drghs-worker/kubernetes/deployment.yaml
- drghs-worker/maintner-swpr/github.go
- drghs-worker/maintner-swpr/limit_transport.go
- drghs-worker/maintner-swpr/limit_transport_test.go
- drghs-worker/maintner-swpr/main.go
- drghs-worker/maintner-swpr/maint_test.go
1. Split code into more logical groups
2. Added Cloud Error Reporting Client to report any errors that occur
3. An error when processing a repository does not abort the entire job,
rather it logs and reports the error and continues
4. Prints a summary of all errors encountered at the end of the job
> feat(maintner-swpr): refactors and error retries

- .github/CODEOWNERS
Adds orthros and jmdobry as CODEOWNERS
> chore: add CODEOWNERs to repository

- samplr/git_repository.go
Previously, samplr would attempt to pull the commits from origin/master
which would cause a hard exit on the daemon process.
Now, only pull on a first iteration through the branches and when the
branch is the "master" branch.
Also remove unneded error group
> fix(samplr): handle repos with no master branch

- samplr/samplr-sprvsr/main.go
> fix(samplrd): increase memory limit to 2.5G from 1.5G

- drghs-worker/maintnerd/api/v1beta1/common.go
- drghs-worker/maintnerd/api/v1beta1/common_test.go
> feat(maintnerd): Add field_mask support to comments.

- samplr/git-go/commit_test.go
- samplr/samplrd/filter/filters_test.go
> chore(samplr): fix vet errors in tests

- leif/find_slo_doc.go
- leif/leifd/leifapi/slo_service.go
It was listing the slos for the repositories instead of the overarching slos
> fix(leif): ListOwnerSlos does not list slos for the repos

- drghs-worker/pkg/sloutils/slo_utils.go
- drghs-worker/pkg/sloutils/slo_utils_test.go
> feat(maintner): add func to test if SLO applies

- drghs-worker/go.sum
- drghs-worker/pkg/sloutils/slo_utils.go
- drghs-worker/pkg/sloutils/slo_utils_test.go
Function to check for how long issue is compliant until or how long it has not been compliant if OOSLO
> feat(maintner): add func to check issue compliancy

- drghs-worker/kubernetes/deployment.yaml
- drghs-worker/maintner-rtr/main.go
- drghs-worker/maintner-rtr/main_test.go
- drghs-worker/maintnerd/main.go
> fix(maintner): add 404 error codes

- samplr/samplr-sprvsr/main.go
- sprvsr/k8s_supervisor.go
- sprvsr/k8s_supervisor_test.go
sprvsr now detects if the default branch has changed and will recreate deployments as appropriate
> fix(sprvsr): recreate Deployments when the default branch changes

- samplr/snippet.go
- samplr/snippet_test.go
> feat(samplr): add support for .tf files (HCL)
